var MSG = {
  ArduinoWarningTitle: "Попередження",
  ArduinoWarning: "У режимі редагування Arduino особливості графічного редактора обмежується основами графічного програмування. Середовища симуляції, так як і можливість завантаження на фізичне обладнання, не підтримується!",
  arduinoCodeCopied: "Код Arduino скопійовано в буфер обміну",
  title: "DwenguinoBlockly",
  blocks: "Блоки",
  linkTooltip: "Зберегти та з'єднати з блоками.",
  runTooltip: "Запустити програму, складену блоками в робочій області.",
  loadBlocksFileTooltip: "Завантажити файл блоків, збережений раніше",
  saveBlocksFileTooltip: "Зберегти блоки у локальний файл",
  toggleSimulator: "Перейти до симулятора.",
  badCode: "Помилка програми:\n%1",
  timeout: "Перевищено максимальну кількість ітерацій.",
  trashTooltip: "Позбутися всіх блоків.",
  catLogic: "Логічні вирази",
  catLoops: "Цикли",
  catMath: "Математика",
  catText: "Текст",
  catLists: "Списки",
  catColour: "Колір",
  catArduino: "Arduino",
  catVariables: "Змінні величини",
  catFunctions: "Функції",
  catDwenguino: "Dwenguino",
  catSocialRobot: "Соціальний робот",
  catInput: "Ввід",
  catOutput: "Вивід",
  catConveyor: "Конвеєр",
  catComments: "Коментарі",
  catBoardIO: "IO",
  copy: "Копіювати",
  createVar: "Створити змінну",
  examples: "Приклади",
  listVariable: "список",
  textVariable: "текст",
  httpRequestError: "Виникла проблема з запитом.",
  linkAlert: "Поділіться своїми блоками за цим покликанням:\n\n%1",
  hashError: "Вибачте, '%1' не відповідає жодній збереженій програмі.",
  xmlError: "Не вдалося завантажити збережений файл. Можливо, його було створено іншою версією Blockly?",
  badXml: "Помилка аналізу XML:\n%1\n\Виберіть 'OK' щоб відмовитись від ваших змін, чи 'Закрити' для подальшого редагування XML.",
  setup: "налаштування",
  loop: "цикл",
  dwenguino_main_program_structure: "Код у блоці налаштування виконується один раз під час запуску програми. Код у циклі повторюється до зупинки програми.",
  catDwenguino: "Dwenguino",
  delay_help: "Зачекайти вказану кількість мілісекунд (1 секунда = 1000 мілісекунд)",
  delay: "delay",
  clearLCD: "Очистити РК-дисплей",
  dwenguinoLCD: "Dwenguino РК-дисплей %1 %2 %3 Написати текст: %4 У рядку: %5 Починаючи з колонки: %6",
  pin: "закріпити",
  toneOnPin: "Увімкнути звук ",
  frequency: "з частотою",
  noToneOnPin: "Зупинити звук",
  
  
  
  //TODO: translate
  toneOnPinTooltip: "Play tone with specific frequency on specified pin",
  noToneOnPinTooltip: "Stop tone on pin",
  sonarTooltip: "This sensor reads the distance from a sonar sensor",
  pirTooltip: "Цей датчик може виявляти рух",
  miliseconds: "мс",
  digitalRead: "Зчитати цифрове значення з",
  digitalWriteToPin: "Write on",
  digitalWriteValue: "цифрове значення",
  digitalWriteTooltip: "Write high or low value to a digital pin of the Dwenguino board",
  digitalReadTooltip: "Read a digital value (1/high or 0/low) from a specified pin",
  high: "HIGH",
  low: "LOW",
  highLowTooltip: "Represents a high (1) or low (0) value on a pin.",
  tutsIntroduction: "Вступ",
  tutsTheremin: "Theremin",
  tutsRobot: "Робот",
  tutsHelloDwenguino: "Привіт, Dwenguino!",
  tutsNameOnLcd: "Name on LCD",
  tutsBlinkLED: "Blink LED",
  tutsLedOnButtonPress: "LED on button press",
  tutsBitPatternOnLeds: "Bit pattern on LEDs",
  tutsAllButtons: "All buttons",
  tutsDriveForward: "Drive forward",
  tutsRideInSquare: "Ride a square",
  tutsRideToWall: "Ride to wall",
  tutsAvoidWall: "Avoid wall",
  tutsNameOnLcdBasic: "Your name on LCD",
  simulator: "Simulator",
  setLedState: "Turn %1 %2",
  setLedStateTooltip: "Turn an LED on the Dwenguino board on or off",
  ledPinsTooltip: "Pick a LED you want to control",
  dwenguinoOn: "ON",
  dwenguinoOff: 'OFF',
  dwenguinoOnOffTooltip: "Select a value to turn an LED ON or OFF",
  dwenguinoLedBlock: "LED",
  dwenguinoSonarBlock: "sonar %1 %2 %3 trig pin number %4 echo pin number %5",
  dwenguinoServoBlock: "Servo motor %1 %2 %3 pin %4 angle %5",
  dwenguinoServoDropdownBlock: "Servo motor %1",
  dwenguinoServoBlockTooltip: "Set one of the servos connected to the Dwenguino to a specified angle between 0 and 180 degrees",
  dwenguinoServoDropdownTooltip: "Select one of the two internal servo motors",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoDCMotorBlock: "DC Motor %1 %2 %3 channel %4 speed %5",
  dwenguinoDCMotorBlockTooltip: "Set the speed of one of the two Dwenguino motors. Speed = value between -255 (full speed backwards) and 255 (full speed forwards)",
  dwenguinoAnalogWrite: "Write to %1 analog value %2",
  dwenguinoAnalogWriteTooltip: "Написати аналогове значення між 0 та 255 до вказаного pin",
  dwenguinoAnalogRead: "Зчитати аналогове значення з %1",
  dwenguinoAnalogWriteTooltip: "Read a value between 0 and 255 from the specified pin",



  //Example
  title: "Код",
  blocks: "Блоки",
  linkTooltip: "Зберегти і пов'язати з блоками.",
  runTooltip: "Запустіть програму, визначену блоками у робочій області.",
  badCode: "Помилка програми:\n%1",
  timeout: "Максимальне виконання ітерацій перевищено.",
  trashTooltip: "Відкинути всі блоки.",
  catLogic: "Логіка",
  catLoops: "Петлі",
  catMath: "Математика",
  catText: "Текст",
  catLists: "Списки",
  catColour: "Колір",
  catVariables: "Змінні",
  catFunctions: "Функції",
  listVariable: "список",
  textVariable: "текст",
  httpRequestError: "Виникла проблема із запитом.",
  linkAlert: "Поділитися вашим блоками через посилання:\n\n%1",
  hashError: "На жаль, \"%1\" не відповідає жодній збереженій програмі.",
  xmlError: "Не вдалося завантажити ваш збережений файл.  Можливо, він був створений з іншої версії Blockly?",
  badXml: "Помилка синтаксичного аналізу XML:\n%1\n\nВиберіть \"Гаразд\", щоб відмовитися від змін або 'Скасувати' для подальшого редагування XML."
};
